add test and coverage

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -41,6 +41,17 @@ jobs:
       - name: Install Dependencies
         run: ./gradlew build --no-daemon
 
+      - name: Check Coverage
+        run: |
+          COVERAGE=$(./gradlew jacocoTestReport | grep -oP '\d+\.\d+(?=%)')  # Adjust the command to extract the coverage
+          echo "Coverage: $COVERAGE%"
+          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
+            echo "Coverage is below 70%, failing the build."
+            exit 1
+          else
+            echo "Coverage is above 70%"
+          fi
+
       # Authenticate to Google Cloud using Workload Identity Federation (WIF)
       - name: Authenticate to GCP using Workload Identity Federation
         uses: google-github-actions/auth@v2
@@ -78,14 +89,14 @@ jobs:
         run: |-
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             if [[ "${{ github.base_ref }}" == "develop" ]]; then
-              # build docker name for the development Artifact Registry
+        # build docker name for the development Artifact Registry
               docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DEV_ARTIFACTORY }}/domain-registry-service:${{ env.TAG_NAME }} .
             elif [[ "${{ github.base_ref }}" == "release" ]]; then
-              # build docker name for the release Artifact Registry
+        # build docker name for the release Artifact Registry
               docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.RELEASE_ARTIFACTORY }}/domain-registry-service:${{ env.TAG_NAME }} .
             fi
           else
-            # for manual trigger
+        # for manual trigger
             docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/domain-registry-service:${{ env.TAG_NAME }} .
           fi
 
@@ -97,14 +108,14 @@ jobs:
         run: |-
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             if [[ "${{ github.base_ref }}" == "develop" ]]; then
-              # Push to the development Artifact Registry
+        # Push to the development Artifact Registry
               docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DEV_ARTIFACTORY }}/domain-registry-service:${{ env.TAG_NAME }}
 
             elif [[ "${{ github.base_ref }}" == "release" ]]; then
-              # Push to the release Artifact Registry
+        # Push to the release Artifact Registry
               docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.RELEASE_ARTIFACTORY }}/domain-registry-service:${{ env.TAG_NAME }}              
             fi
           else
-            # For pushes or manual triggers, push to the production Artifact Registry
+        # For pushes or manual triggers, push to the production Artifact Registry
             docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/domain-registry-service:${{ env.TAG_NAME }}
           fi
